export enum ErrorType {
    VALIDATION = 'VALIDATION',
    NOT_FOUND = 'NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    CONFLICT = 'CONFLICT',
    INTERNAL = 'INTERNAL',
    PAYMENT_REQURIED = 'PAYMENT_REQURIED',
    RATE_LIMIT = 'RATE_LIMIT',
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
    UNKNOWN = 'UNKNOWN',
}
  